-- =============================================================================
-- PARA COLAR NO SQL EDITOR DO SUPABASE — atualizado em 01/10/2026
-- =============================================================================
-- Pendente: a 38-programado-e-executado.sql.
--
-- Confere antes o que já entrou. A 36 e a 37 também precisam estar aplicadas:
--
--   select numero, arquivo from migracao order by numero;
--
-- Se a última for 35, rode a 36 e a 37 primeiro (estão no histórico da conversa
-- e em db/). A 38 não depende delas, mas as três faltam.
--
-- A tela já funciona antes da 38: ela só passa a mostrar a data original e a
-- tratar a atividade parcial como parcial quando a 38 estiver no banco.
-- =============================================================================
