-- =============================================================================
-- Nada pendente — conferido em 29/09/2026
-- =============================================================================
-- A última aplicada é a 34. Para conferir a qualquer momento:
--
--   select numero, arquivo, to_char(aplicada_em, 'DD/MM HH24:MI') as quando
--   from migracao order by numero;
--
-- E para achar buraco no meio da numeração:
--
--   select g as faltando
--   from generate_series(1, (select max(numero) from migracao)) g
--   where not exists (select 1 from migracao m where m.numero = g);
--
-- Quando houver migração nova para aplicar, este arquivo volta a ser gerado
-- com o que falta, na ordem certa.
-- =============================================================================
